library(readr)
library(dplyr)
library(tidyverse)
library(stringr)
refine<-read_csv("refine.csv")
refine<-mutate(refine, company=tolower(company))
refine$company <- str_replace(refine$company, "phillips", "philips")
refine$company <- str_replace(refine$company, "phllips", "philips")
refine$company <- str_replace(refine$company, "phillps", "philips")
refine$company <- str_replace(refine$company, "fillips", "philips")
refine$company <- str_replace(refine$company, "phlips", "philips")
refine$company <- str_replace(refine$company, "akz0", "akzo")
refine$company <- str_replace(refine$company, "ak zo", "akzo")
refine$company <- str_replace(refine$company, "unilver", "unilever")
refine<-separate(refine, "Product code / number", c("product_code", "product number"))
refine<-mutate(refine, productcategory=product_code)
refine$productcategory<-str_replace(refine$productcategory, "p", "Smartphone")
refine$productcategory<-str_replace(refine$productcategory, "v", "TV")
refine$productcategory<-str_replace(refine$productcategory, "x", "Laptop")
refine$productcategory<-str_replace(refine$productcategory, "q", "Tablet")
refine<-unite(refine, full_address, address, city, country, sep = ",")
refine<-mutate(refine, company_philips=company)
refine$company_philips<-str_replace(refine$company_philips, "philips", "1")
refine$company_philips<-str_replace(refine$company_philips, "akzo", "0")
refine$company_philips<-str_replace(refine$company_philips, "van houten", "0")
refine$company_philips<-str_replace(refine$company_philips, "unilever", "0")
refine<-mutate(refine, company_akzo=company)
refine$company_akzo<-str_replace(refine$company_akzo, "philips", "0")
refine$company_akzo<-str_replace(refine$company_akzo, "akzo", "1")
refine$company_akzo<-str_replace(refine$company_akzo, "van houten", "0")
refine$company_akzo<-str_replace(refine$company_akzo, "unilever", "0")
refine<-mutate(refine, company_van_houten=company)
refine$company_van_houten<-str_replace(refine$company_van_houten, "philips", "0")
refine$company_van_houten<-str_replace(refine$company_van_houten, "akzo", "0")
refine$company_van_houten<-str_replace(refine$company_van_houten, "van houten", "1")
refine$company_van_houten<-str_replace(refine$company_van_houten, "unilever", "0")
refine<-mutate(refine, company_unilever=company)
refine$company_unilever<-str_replace(refine$company_unilever, "philips", "0")
refine$company_unilever<-str_replace(refine$company_unilever, "akzo", "0")
refine$company_unilever<-str_replace(refine$company_unilever, "van houten", "0")
refine$company_unilever<-str_replace(refine$company_unilever, "unilever", "1")
refine<-mutate(refine, product_smartphone=productcategory)
refine$product_smartphone<-str_replace(refine$product_smartphone, "Smartphone", "1")
refine$product_smartphone<-str_replace(refine$product_smartphone, "Laptop", "0")
refine$product_smartphone<-str_replace(refine$product_smartphone, "TV", "0")
refine$product_smartphone<-str_replace(refine$product_smartphone, "Tablet", "0")
refine<-mutate(refine, product_tv=productcategory)
refine$product_tv<-str_replace(refine$product_tv, "TV", "1")
refine$product_tv<-str_replace(refine$product_tv, "Smartphone", "0")
refine$product_tv<-str_replace(refine$product_tv, "Laptop", "0")
refine$product_tv<-str_replace(refine$product_tv, "Tablet", "0")
refine<-mutate(refine, product_laptop=productcategory)
refine$product_laptop<-str_replace(refine$product_laptop, "Laptop", "1")
refine$product_laptop<-str_replace(refine$product_laptop, "TV", "0")
refine$product_laptop<-str_replace(refine$product_laptop, "Smartphone", "0")
refine$product_laptop<-str_replace(refine$product_laptop, "Tablet", "0")
refine<-mutate(refine, product_tablet=productcategory)
refine$product_tablet<-str_replace(refine$product_tablet, "Laptop", "0")
refine$product_tablet<-str_replace(refine$product_tablet, "TV", "0")
refine$product_tablet<-str_replace(refine$product_tablet, "Smartphone", "0")
refine$product_tablet<-str_replace(refine$product_tablet, "Tablet", "1")
